name: musayyer_app
description: Musayyer (مسير) mobile app built with clean architecture.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.5.0+1
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.2.2
  go_router: ^14.2.0
  shared_preferences: ^2.2.3
  provider: ^6.1.2

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
